import { FinancingOption } from "../../types/financing";

export const FINANCING_OPTIONS: FinancingOption[] = [
    {
      bank: "American Express",
      logo: "/images/banks/amex-logo.png",
      cardName: "American Express",
      cardImage: "/images/banks/amex-logo.png",
      plan: "25% OFF",
    },
    {
      bank: "Banco Nación",
      logo: "/images/banks/banco-nacion-logo.png",
      cardName: "Banco Nación",
      cardImage: "/images/banks/banco-nacion-logo.png",
      plan: "Hasta 12 cuotas sin interés",
    },
    {
      bank: "Visa",
      logo: "/images/banks/visa-logo.png",
      cardName: "Visa",
      cardImage: "/images/banks/visa-logo.png",
      plan: "Hasta 6 cuotas sin interés",
    },
    {
      bank: "Mastercard",
      logo: "/images/banks/mastercard-logo.png",
      cardName: "Mastercard",
      cardImage: "/images/banks/mastercard-logo.png",
      plan: "Hasta 3 cuotas sin interés",
    },
    {
      bank: "Cencosud",
      logo: "/images/banks/cencosud.png",
      cardName: "Tarjeta Cencosud",
      cardImage: "/images/banks/cencosud.png",
      plan: "20% OFF + 6 cuotas sin interés",
    },
    {
      bank: "CencoPay",
      logo: "/images/banks/cencopay.png",
      cardName: "CencoPay",
      cardImage: "/images/banks/cencopay.png",
      plan: "25% OFF + 3 cuotas sin interés",
    },
    // 🆕 Logos adicionales de bancos argentinos
    {
      bank: "Banco BBVA",
      logo: "/images/banks/BancoBBVA.jpg",
      cardName: "Banco BBVA",
      cardImage: "/images/banks/BancoBBVA.jpg",
      plan: "Hasta 12 cuotas sin interés",
    },
    {
      bank: "Banco Ciudad",
      logo: "/images/banks/BancoCiudad.jpg",
      cardName: "Banco Ciudad",
      cardImage: "/images/banks/BancoCiudad.jpg",
      plan: "Hasta 6 cuotas sin interés",
    },
    {
      bank: "Banco Galicia",
      logo: "/images/banks/BancoGalicia.jpg",
      cardName: "Banco Galicia",
      cardImage: "/images/banks/BancoGalicia.jpg",
      plan: "Hasta 12 cuotas sin interés",
    },
    {
      bank: "Banco Hipotecario",
      logo: "/images/banks/BancoHipotecario.jpg",
      cardName: "Banco Hipotecario",
      cardImage: "/images/banks/BancoHipotecario.jpg",
      plan: "Hasta 6 cuotas sin interés",
    },
    {
      bank: "Banco ICBC",
      logo: "/images/banks/BancoICBC.jpg",
      cardName: "Banco ICBC",
      cardImage: "/images/banks/BancoICBC.jpg",
      plan: "Hasta 18 cuotas sin interés",
    },
    {
      bank: "Banco Macro",
      logo: "/images/banks/BancoMacro.jpg",
      cardName: "Banco Macro",
      cardImage: "/images/banks/BancoMacro.jpg",
      plan: "Hasta 12 cuotas sin interés",
    },
    {
      bank: "Banco Supervielle",
      logo: "/images/banks/BancoSupervielle.jpg",
      cardName: "Banco Supervielle",
      cardImage: "/images/banks/BancoSupervielle.jpg",
      plan: "Hasta 6 cuotas sin interés",
    },
    {
      bank: "Tarjeta Naranja",
      logo: "/images/banks/Naranja.jpg",
      cardName: "Tarjeta Naranja",
      cardImage: "/images/banks/Naranja.jpg",
      plan: "20% OFF + hasta 18 cuotas",
    },
    {
      bank: "Tarjeta Cordobesa",
      logo: "/images/banks/Cordobesa.jpg",
      cardName: "Tarjeta Cordobesa",
      cardImage: "/images/banks/Cordobesa.jpg",
      plan: "15% OFF + hasta 12 cuotas",
    },
    {
      bank: "Visa & Mastercard",
      logo: "/images/banks/VISAMastercard.jpg",
      cardName: "Visa & Mastercard",
      cardImage: "/images/banks/VISAMastercard.jpg",
      plan: "Hasta 6 cuotas sin interés",
    },
    // 🆕 Opciones combinadas de CencoPay
    {
      bank: "CencoPay - Galicia, Nación, Hipotecario",
      logo: "/images/banks/CencopayGaliciaNacHipotecario.jpg",
      cardName: "CencoPay Multi-banco",
      cardImage: "/images/banks/CencopayGaliciaNacHipotecario.jpg",
      plan: "Hasta 12 cuotas sin interés",
    },
    {
      bank: "CencoPay - Visa & Mastercard",
      logo: "/images/banks/CencopayVisaMastercard.jpg",
      cardName: "CencoPay Visa & Mastercard",
      cardImage: "/images/banks/CencopayVisaMastercard.jpg",
      plan: "Hasta 6 cuotas sin interés",
    },
    {
      bank: "CencoPay - Crédito",
      logo: "/images/banks/Cencopaycredito.jpg",
      cardName: "CencoPay Crédito",
      cardImage: "/images/banks/Cencopaycredito.jpg",
      plan: "Hasta 24 cuotas",
    },
  ];